import RateOfGrowth from "./components/calculators/RateOfGrowth";
import GrowthTarget from "./components/calculators/GrowthTarget";
import BasicFinancialPlanner from "./components/calculators/BasicFinancialPlanner";
import FedRates from "./components/calculators/FedRates";
import ProgressiveTax from "./components/calculators/ProgressiveTax";
import BlendedInvestment from "./components/calculators/BlendedInvestment";
import StockAnalysis from "./components/calculators/StockAnalysis";
import PortfolioInMultipleCcys from "./components/calculators/PortfolioInMultipleCcys";
import PortfolioShockMatrix from "./components/calculators/PortfolioShockMatrix";
import RetirementPlanner from "./components/calculators/RetirementPlanner";
import RatingsBasedPredictor from "./components/calculators/RatingsBasedPredictor";
import CorporateDebtTaxSaver from "./components/calculators/CorporateDebtTaxSaver";

export const CALCULATORS_AND_SIMULATORS = [
  {
    name: "Basic Financial Planner",
    value: "basicfinancialplanner",
    tags: ["finance", "planning"],
    description:
      "A simple tool to plan your financial future based on corpus, expenses, and growth.",
    panel: BasicFinancialPlanner,
  },
  // {
  //   name: "FX Rates",
  //   value: "fxrates",
  //   tags: ["finance", "forex"],
  //   description: "Historical FX rates for fiat currencies.",
  //   panel: FXRates,
  // },
  {
    name: "Fed Rates",
    value: "fedrates",
    tags: ["finance", "economics", "fed"],
    description:
      "Federal Reserve interest rates (EFFR, SOFR, etc.) from the NY Fed API.",
    panel: FedRates,
  },
  {
    name: "Growth Target",
    value: "growthtarget",
    tags: ["finance", "planning", "investment"],
    description:
      "Calculate the required annual growth rate to reach a target amount over time.",
    panel: GrowthTarget,
  },
  {
    name: "Progressive Tax",
    value: "progressivetax",
    tags: ["finance", "tax", "investment"],
    description:
      "Calculate progressive tax based on custom brackets and income.",
    panel: ProgressiveTax,
  },
  {
    name: "Rate of Growth",
    value: "rateofgrowth",
    tags: ["finance", "economics"],
    description:
      "The rate at which a variable increases over a specific period of time.",
    panel: RateOfGrowth,
  },
  {
    name: "Blended Investment",
    value: "blendedinvestment",
    tags: ["finance", "planning", "investment"],
    description:
      "Project growth of a portfolio with multiple different investment types and rates.",
    panel: BlendedInvestment,
  },
  {
    name: "Stock Analysis",
    value: "stockanalysis",
    tags: ["finance", "stocks", "investing"],
    description:
      "Analyze stock price history from CSV files with interactive charts.",
    panel: StockAnalysis,
  },
  {
    name: "Portfolio in Currencies",
    value: "portfolioinmultipleccys",
    tags: ["finance", "portfolio", "forex"],
    description:
      "Analyze and track investment portfolios across multiple currencies.",
    panel: PortfolioInMultipleCcys,
  },
  {
    name: "Portfolio Shock Analaysis",
    value: "portfolioshockmatrix",
    tags: ["finance", "portfolio", "risk", "simulation"],
    description:
      "Simulate and visualize the impact of market shocks (-40% to +40%) on your investment portfolio.",
    panel: PortfolioShockMatrix,
  },
  {
    name: "Retirement Plan Tool",
    value: "retirementplanner",
    tags: ["finance", "planning", "retirement"],
    description:
      "Plan your retirement savings accumulation and withdrawal phases, with inflation adjustment and depletion analysis.",
    panel: RetirementPlanner,
  },
  {
    name: "Ratings Based Predictor",
    value: "ratingsbasedpredictor",
    tags: ["statistics", "planning", "risk", "simulation"],
    description:
      "Predict your personal experience score and risk based on rating distribution, sample size, and Bayesian average estimation.",
    panel: RatingsBasedPredictor,
  },
  {
    name: "Corporate Debt Tax Saver",
    value: "corporatedebttaxsaver",
    tags: ["finance", "tax", "planning"],
    description:
      "Calculate interest tax shields, net tax savings, and effective tax rates generated by corporate debt interest deductibility.",
    panel: CorporateDebtTaxSaver,
  },
];

export { getTagStyles } from "./utils/color";
